# Use Ubuntu as the base image
# FROM ubuntu:20.04
FROM --platform=linux/amd64 python:3.11

# update and install nginx
RUN	apt-get update
RUN	apt-get install -y --no-install-recommends nginx

# set the working directory
WORKDIR /regression_test_suite

# copy everything to container
COPY ./ .

# install dependent packages
RUN pip3 install --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org
RUN pip3 install -r requirements.txt --trusted-host pypi.org --trusted-host files.pythonhosted.org
RUN pip3 install ./dependencies/ascendops_commonlib-0.4.4.tar.gz --trusted-host pypi.org --trusted-host files.pythonhosted.org

# expose the port the app runs on
EXPOSE 3000

# infra config
ENV PYTHONPATH=.:/
ENV RUNTIME_ENV=prod
ENV DEFAULT_REGION=us-east-1
ENV APP_DIR=/regression_test_suite
ENV SECRETS_ENV=test
ENV SECURITY_PROTOCOL=SSL

# app config
ENV ES_TESTCASES_DB_NAME=rts_testcases

# kafka config
ENV MSK_BOOTSTRAP_SERVERS=b-1.prod-go-msk.q6kn9y.c3.kafka.us-east-1.amazonaws.com:9094,b-2.prod-go-msk.q6kn9y.c3.kafka.us-east-1.amazonaws.com:9094,b-3.prod-go-msk.q6kn9y.c3.kafka.us-east-1.amazonaws.com:9094
ENV PUBLIC_CERT_S3_PATH=certs/prod-public-cert.pem
ENV PRIVATE_KEY_S3_PATH=certs/prod-private-key.pem
ENV PUBLIC_CERT_FILE_NAME=prod-public-cert.pem
ENV PRIVATE_KEY_FILE_NAME=prod-private-key.pem
ENV KAFKA_NO_CONSUMER_PER_INSTANCE=8
ENV AUDIT_LOG_TOPIC=test_audit_log

# es config
ENV DEFAULT_ES_HOST=vpc-prod-ascend-go-exjny3wjz543dpb6yrhfys43vm.us-east-1.es.amazonaws.com
ENV DEFAULT_ES_PORT=443
ENV DEFAULT_ES_ROLE=arn:aws:iam::262403030294:role/prod-es-role

# start the app
CMD ["python","audit_log_app_server.py"]
