# Use Ubuntu as the base image
# FROM ubuntu:20.04
FROM --platform=linux/amd64 python:3.11

# update and install nginx
RUN	apt-get update
RUN	apt-get install -y --no-install-recommends nginx

# set the working directory
WORKDIR /regression_test_suite

# copy everything to container
COPY ./ .

# install dependent packages
RUN pip3 install --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org
RUN pip3 install -r requirements.txt --trusted-host pypi.org --trusted-host files.pythonhosted.org
RUN pip3 install ./dependencies/ascendops_commonlib-0.4.4.tar.gz --trusted-host pypi.org --trusted-host files.pythonhosted.org

# expose the port the app runs on
EXPOSE 3000

# infra config
ENV PYTHONPATH=.:/
ENV RUNTIME_ENV=uat
ENV DEFAULT_REGION=us-east-1
ENV APP_DIR=/regression_test_suite
ENV SECRETS_ENV=uat
ENV SECURITY_PROTOCOL=SSL

# app config
ENV ES_TESTCASES_DB_NAME=expn-ascend-ops-rts-testcases

# kafka config
ENV MSK_BOOTSTRAP_SERVERS=b-1.uat-go-msk.fh6081.c3.kafka.us-east-1.amazonaws.com:9094,b-2.uat-go-msk.fh6081.c3.kafka.us-east-1.amazonaws.com:9094
ENV KAFKA_NO_CONSUMER_PER_INSTANCE=2
ENV AUDIT_LOG_NUM_PROCESSES=6

# es config
ENV DEFAULT_ES_HOST=vpc-uat-ascend-go-wdae7basbpxdvkgtpnicgu53jm.us-east-1.es.amazonaws.com
ENV DEFAULT_ES_PORT=443
ENV DEFAULT_ES_ROLE=arn:aws:iam::262403030294:role/uat-es-role

# start the app
CMD ["python","audit_log_app_server.py"]
